package com.ayue.springboot.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.ayue.springboot.db.po.Player;
import com.ayue.springboot.db.po.PlayerExample;

@Repository
public interface PlayerMapper {
        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        long countByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int deleteByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int insert(Player record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int insertSelective(Player record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        List<Player> selectByExample(PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        Player selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int updateByPrimaryKeySelective(Player record);

        /**
         * This method was generated by MyBatis Generator. This method
         * corresponds to the database table player
         *
         * @mbg.generated Thu Jul 02 16:46:16 CST 2020
         */
        int updateByPrimaryKey(Player record);
}