package com.ayue.springboot.db.po;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.user_id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.art
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private String art;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.power
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private Integer power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.diamond
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    private Integer diamond;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.user_id
     *
     * @return the value of player.user_id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.user_id
     *
     * @param userId the value for player.user_id
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.art
     *
     * @return the value of player.art
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public String getArt() {
        return art;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.art
     *
     * @param art the value for player.art
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setArt(String art) {
        this.art = art;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.power
     *
     * @return the value of player.power
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.power
     *
     * @param power the value for player.power
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.diamond
     *
     * @return the value of player.diamond
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public Integer getDiamond() {
        return diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.diamond
     *
     * @param diamond the value for player.diamond
     *
     * @mbg.generated Thu Jul 02 16:46:16 CST 2020
     */
    public void setDiamond(Integer diamond) {
        this.diamond = diamond;
    }
}